//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cookbook.Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class ClientSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ClientSettings defaultInstance = ((ClientSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ClientSettings())));
        
        public static ClientSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:5213/")]
        public string ApiUrl {
            get {
                return ((string)(this["ApiUrl"]));
            }
            set {
                this["ApiUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/recipes")]
        public string UrlGetRecipes {
            get {
                return ((string)(this["UrlGetRecipes"]));
            }
            set {
                this["UrlGetRecipes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories")]
        public string UrlGetCategories {
            get {
                return ((string)(this["UrlGetCategories"]));
            }
            set {
                this["UrlGetCategories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories/recipe")]
        public string UrlGetCategoriesByRecipeId {
            get {
                return ((string)(this["UrlGetCategoriesByRecipeId"]));
            }
            set {
                this["UrlGetCategoriesByRecipeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories")]
        public string UrlPostCategory {
            get {
                return ((string)(this["UrlPostCategory"]));
            }
            set {
                this["UrlPostCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories/recipe")]
        public string UrlPostCategoryByRecipeId {
            get {
                return ((string)(this["UrlPostCategoryByRecipeId"]));
            }
            set {
                this["UrlPostCategoryByRecipeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories")]
        public string UrlPutCategory {
            get {
                return ((string)(this["UrlPutCategory"]));
            }
            set {
                this["UrlPutCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories")]
        public string UrlDeleteCategory {
            get {
                return ((string)(this["UrlDeleteCategory"]));
            }
            set {
                this["UrlDeleteCategory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories/recipe")]
        public string UrlRemoveCategoryByRecipeId {
            get {
                return ((string)(this["UrlRemoveCategoryByRecipeId"]));
            }
            set {
                this["UrlRemoveCategoryByRecipeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/authentication/signin")]
        public string UrlSignIn {
            get {
                return ((string)(this["UrlSignIn"]));
            }
            set {
                this["UrlSignIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/ingredients/recipe")]
        public string UrlGetIngredientsByRecipeId {
            get {
                return ((string)(this["UrlGetIngredientsByRecipeId"]));
            }
            set {
                this["UrlGetIngredientsByRecipeId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("admin")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v1/cookbook/categories/recipe")]
        public string UrlAddCategoryByRecipeId {
            get {
                return ((string)(this["UrlAddCategoryByRecipeId"]));
            }
            set {
                this["UrlAddCategoryByRecipeId"] = value;
            }
        }
    }
}
