###
POST {{Cookbook}}/v1/authentication/signup
Content-Type: application/json

{
  "Username": "adminwannabe",
  "Email": "adminwannabe@adminwannabe.com",
  "Password": "adminwannabe"
}
> {%
    if (response.status === 200 || response.status === 201) {
        client.global.set('auth_token', response.body.token);
    } else {
        client.log('Sign-Up failed with status: ' + response.status);
        client.global.clear('auth_token'); // Clear token if sign-in fails
    }
%}

###

POST {{Cookbook}}/v1/authentication/signin
Content-Type: application/json

{
  "Username": "adminwannabe",
  "Password": "adminwannabe"
}
> {%
    if (response.status === 200 || response.status === 201) {
        client.global.set('auth_token', response.body.token);
    } else {
        client.log('Sign-in failed with status: ' + response.status);
        client.global.clear('auth_token'); // Clear token if sign-in fails
    }
%}

###

POST {{Cookbook}}/v1/authentication/signin
Content-Type: application/json

{
  "Username": "user",
  "Password": "user"
}
> {%
    if (response.status === 200 || response.status === 201) {
        client.global.set('auth_token', response.body.token);
    } else {
        client.log('Sign-in failed with status: ' + response.status);
        client.global.clear('auth_token'); // Clear token if sign-in fails
    }
%}

###

POST {{Cookbook}}/v1/cookbook/Recipes/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "sdf",
  "difficulty": 1,
  "imagePath": "sdf",
  "ingredients": [
    {
      "ingredientId": 1,
      "quantity": 1,
      "unit": null
    }
  ],
  "categories": [
    {
      "categoryId": 1
    }
  ],
  "steps": [
    {
      "stepNumber": 1,
      "instruction": "sdf",
      "duration": "20:20:20",
      "isCooking": true
    }
  ]
}

###
PUT {{Cookbook}}/v1/cookbook/Recipes/12
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "title": "sdf",
  "difficulty": 1,
  "imagePath": "sdf",
  "ingredients": [
    {
      "ingredientId": 1,
      "quantity": 2,
      "unit": "help"
    }
  ],
  "categories": [
    {
      "categoryId": 2
    },
    {
      "categoryId": 3
    }
  ],
  "steps": [
    {
      "stepNumber": 1,
      "instruction": "sdf",
      "duration": "20:20:20",
      "isCooking": true
    },
    {
      "stepNumber": 2,
      "instruction": "sdfsdfdfg",
      "duration": "00:20:20",
      "isCooking": true
    }
  ]
}

###
POST {{Cookbook}}/v1/cookbook/Categories/
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Testeded"
}

###
GET {{Cookbook}}/v1/cookbook/Recipes/13/full
Authorization: Bearer {{auth_token}}
Accept: application/json
